/**
 * Find state ids while the SVG is open.
 * Skips numeric ids. The rest should be counties.
 */
function findIds() {
	// only children of main group
	// `<svg> → <g stroke="black" fill="white"> → <path/g id>`
	var ids = [...document.querySelectorAll('svg > g > [id]')]
		.map(el=>el.id)
		.filter(id=>id.replace(/[0-9]+/, '').length>1)
	;
	console.log(ids.length);
	copy(ids);
}
function whResize() {
	var divide = 3.5;

	var svg = document.querySelector('svg');
	var width = svg.getAttribute('width');
	var height = svg.getAttribute('height');
	function resize(x) {
		return (Number.parseFloat(x) / divide).toFixed(2);
	}
	width=resize(width);
	height=resize(height);
	console.log(`width="${width}" height="${height}"`)
}
// findIds();whResize();

let stateName = 'Georgia';
let srcFilePath = `img/Map_of_${stateName}.svg`;
let destFileTemplate = (id)=>`Map_of_${stateName}_highlighting_${id}_County.svg`;

const counties = [
	"Appling",
	"Atkinson",
	"Bacon",
	"Baker",
	"Baldwin",
	"Banks",
	"Barrow",
	"Bartow",
	"Ben_Hill",
	"Berrien",
	"Bibb",
	"Bleckley",
	"Brantley",
	"Brooks",
	"Bryan",
	"Bulloch",
	"Burke",
	"Butts",
	"Calhoun",
	"Camden",
	"Candler",
	"Carroll",
	"Catoosa",
	"Charlton",
	"Chatham",
	"Chattahoochee",
	"Chattooga",
	"Cherokee",
	"Clarke",
	"Clay",
	"Clayton",
	"Clinch",
	"Cobb",
	"Coffee",
	"Colquitt",
	"Columbia",
	"Cook",
	"Coweta",
	"Crawford",
	"Crisp",
	"Dade",
	"Dawson",
	"DeKalb",
	"Decatur",
	"Dodge",
	"Dooly",
	"Dougherty",
	"Douglas",
	"Early",
	"Echols",
	"Effingham",
	"Elbert",
	"Emanuel",
	"Evans",
	"Fannin",
	"Fayette",
	"Floyd",
	"Forsyth",
	"Franklin",
	"Fulton",
	"Gilmer",
	"Glascock",
	"Glynn",
	"Gordon",
	"Grady",
	"Greene",
	"Gwinnett",
	"Habersham",
	"Hall",
	"Hancock",
	"Haralson",
	"Harris",
	"Hart",
	"Heard",
	"Henry",
	"Houston",
	"Irwin",
	"Jackson",
	"Jasper",
	"Jeff_Davis",
	"Jefferson",
	"Jenkins",
	"Johnson",
	"Jones",
	"Lamar",
	"Lanier",
	"Laurens",
	"Lee",
	"Liberty",
	"Lincoln",
	"Long",
	"Lowndes",
	"Lumpkin",
	"Macon",
	"Madison",
	"Marion",
	"McDuffie",
	"McIntosh",
	"Meriwether",
	"Miller",
	"Mitchell",
	"Monroe",
	"Montgomery",
	"Morgan",
	"Murray",
	"Muscogee",
	"Newton",
	"Oconee",
	"Oglethorpe",
	"Paulding",
	"Peach",
	"Pickens",
	"Pierce",
	"Pike",
	"Polk",
	"Pulaski",
	"Putnam",
	"Quitman",
	"Rabun",
	"Randolph",
	"Richmond",
	"Rockdale",
	"Schley",
	"Screven",
	"Seminole",
	"Spalding",
	"Stephens",
	"Stewart",
	"Sumter",
	"Talbot",
	"Taliaferro",
	"Tattnall",
	"Taylor",
	"Telfair",
	"Terrell",
	"Thomas",
	"Tift",
	"Toombs",
	"Towns",
	"Treutlen",
	"Troup",
	"Turner",
	"Twiggs",
	"Union",
	"Upson",
	"Walker",
	"Walton",
	"Ware",
	"Warren",
	"Washington",
	"Wayne",
	"Webster",
	"Wheeler",
	"White",
	"Whitfield",
	"Wilcox",
	"Wilkes",
	"Wilkinson",
	"Worth"
];

module.exports = {
	counties,
	srcFilePath,
	destFileTemplate,
};
